# Generated by Django 5.0.2 on 2024-03-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
